### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by jeffmendoza** [fog/fog-azure#1]
@geemus What is the release process for fog-foo gems? Is there a fog org rubygems account?

**Comment by geemus** [comment]
Not presently (though perhaps there should be). We have just had the individual maintainers register the gem (and add me as a collaborator). Perhaps not ideal, but it has been good-enough so far. Thanks!

**Comment by jeffmendoza** [comment]
Ah ok, Shall we go ahead and do the same?

**Comment by geemus** [comment]
Sounds good to me, thanks!

**Comment by geemus** [comment]
Well done!
