### ISSUE TITLE
Azure Resource Manager

### ISSUE THREAD

**Issue by neillturner** [fog/fog-azure#15]
I've been trying to understand the Azure Resource Manager. It appears microsoft are introduction a new api. So there are 2 APIs now: 
1,  Azure Service Management (ASM) the old API that fog ruby is currently implementing
and a new API,
2.  The Azure Resource Manager (ARM) API - a JSON-driven REST API to interact with Azure cloud resources.
as per: 
http://trevorsullivan.net/2015/08/10/azure-resource-manager-or-service-management/
this  software is useful for accessing ARM 
http://blog.davidebbo.com/2015/01/azure-resource-manager-client.html. 

So it looks to me liike fog needs to create a new project azure-resource-manager to implement this new api. Currently the https://github.com/Azure/azure-sdk-for-ruby doesn't implement the ARM.

Personally i particularly interested in implementing cloudformation equivalent functionality for azure in ruby so i can then build tools. 

Azure is now the number 2 cloud now by usage so should become more popular in fog too.
I'm not an azure expert, i'm just trying to promote discussion and direction for the azure support in fog.

**Comment by neillturner** [comment]
there is a ruby implementation of ARM at
https://github.com/djberg96/azure-armrest

**Comment by kpgriffith** [comment]
Looks like ARM is now supported by the Azure SDK, https://github.com/Azure/azure-sdk-for-ruby/tree/master/resource_management

**Comment by jeffmendoza** [comment]
See #23 now
