### ISSUE TITLE
Azure is not a recognised provider

### ISSUE THREAD

**Issue by ben-houghton-zz** [fog/fog-azure#21]
Hi All

I'm trying to get a test implementation of fog-azure up and running but seem to be having some troubles. I took some examples out of the getting started.md and wrote a small test script like this -

require 'fog'

azure = Fog::Compute.new(
  :provider => :azure,
  :azure_sub_id => '35a2461c-22ac-1111-5ed2-11165d755ba4',
  :azure_pem =>    'C:\Devkit\AzureDir\Azureuser.pem',
  :azure_api_url => 'usnorth.management.core.windows.net'
)

then executed it at command prompt - 

C:\Devkit\AzureDir>ruby fogtest.rb
C:/Ruby22/lib/ruby/gems/2.2.0/gems/fog-core-1.36.0/lib/fog/core/services_mixin.rb:12:in `new': azure is not a recognized provider (ArgumentError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/fog-core-1.36.0/lib/fog/compute.rb:65:in`new'
        from fogtest.rb:6:in `<main>'

I have installed fog-azure using  gem install fog-azure

Can anyone help me with where I'm going wrong?

Thanks

Ben

**Comment by jeffmendoza** [comment]
try `:provider => "Azure",`

**Comment by ben-houghton-zz** [comment]
Thanks for the speedy reply Jeff. I modfied as suggested but still the same error

require 'fog'
require 'pp'

azure = Fog::Compute.new(
  :provider => "Azure",
  :azure_sub_id => '35a2461c-22ac-1111-5ed2-11165d755ba4',
  :azure_pem =>    'C:\Devkit\AzureDir\Azureuser.pem',
  :azure_api_url => 'usnorth.management.core.windows.net'
)

When I look in the provider gemfiles I don't see an Azure one 
![fog-azure1](https://cloud.githubusercontent.com/assets/17010534/13711642/93b09f68-e7b7-11e5-9692-7844062005ac.JPG)

But I do see the fog-azure-0.0.1 gem folder
![fog-azure2](https://cloud.githubusercontent.com/assets/17010534/13711661/b97d0d94-e7b7-11e5-97ea-855c9711d8e0.JPG)

Perhaps I haven't installed a library correctly?

**Comment by jeffmendoza** [comment]
you might just need to `require 'fog-azure'`

**Comment by ben-houghton-zz** [comment]
Thanks, I'm trying that - 

C:\Devkit\AzureDir>ruby fogtest.rb
C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fog-azure (LoadError)
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from fogtest.rb:2:in `<main>'

I've tried altering the prescedence in 'require' statement too

**Comment by jeffmendoza** [comment]
Hmm, not sure why it can't be found. It looks like it is there from your screen shot, maybe you can verify with the `gem` command that it is installed.

**Comment by ben-houghton-zz** [comment]
Hi Jeff

The library seems to be be installed, and I've tried to re-install. I'm running on a Windows 10 laptop, I may try and install on a Linux box and see if that get me any further 

![fog-azure15](https://cloud.githubusercontent.com/assets/17010534/13740905/23f64464-e9cb-11e5-974d-f09d3c682226.JPG)

![fog-azure16](https://cloud.githubusercontent.com/assets/17010534/13740874/fa1a5586-e9ca-11e5-9e24-2763b73e277c.JPG)

**Comment by shaffan-chaudhry-confiz** [comment]
@benh001 
Try this:
`require 'fog/azure'`
It worked for me.

**Comment by dLobatog** [comment]
This is just due to https://github.com/fog/fog-azure/pull/5 - the gem needs a new release with the dependency. Until then, a workaround is to require the `azure` gem manually on your application.

**Comment by parthasarathi204** [comment]
How will I register a new fog storage service provider ? I have developed and installed an new new gem fog-oabc
trying to create Fog::Storage.new(    :provider => 'OABC',.....)  erroring out as /var/lib/gems/2.3.0/gems/fog-core-1.44.2/lib/fog/core/services_mixin.rb:18:in `rescue in new': oabc has no storage service (Fog::Service::NotFound)
